In [1]:
# Numpy is a multi-dimentional array library.
# Can use numpy to store all sorts of data -- one dimentional arrays
# two dimentional arrays etc.
# Comparing to numpy, lists are very slow. Numpy is fast because numpy uses
# fixed type. It uses less bytes of memory, is uses contiguous memory, all
# information is right next to each other in computer's memory. It is not
# like list, the information is scattered around in the computer's memory.
# No type checking when iterating.
# Applications of numpy: matlab repalcement, bc you can do a lot of calculations
# using numpy; Plotting as Matplotlib replacement; it is the backend of the pandas
# library, it allows pandas to work; it is important for machine learning applications,
# the key point tensor in ML is pretty similiar with the numpy library, just the way to
# store all sorts of values.


# Load in Numpy
import numpy as np

# The basics
# Initialize array
# One dimensional
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
# Two dimensional
b = np.array([[3.0, 7.0, 5.0], [6.0, 2.0, 4.0]])
print(b)

[[3. 7. 5.]
 [6. 2. 4.]]


In [3]:
# To get dimension, using ndim
print(b.ndim)

2


In [4]:
# To get shape of the dimesion, using shape
print(b.shape)

(2, 3)


In [5]:
# To get the data type default version, using dtype
print(b.dtype)

float64


In [6]:
# If want to specify the data type, do
b = np.array([[3.0, 7.0, 5.0], [6.0, 2.0, 4.0]], dtype= 'int16')
print(b.dtype)

int16


In [7]:
# Get size using itemsize,
# because currently the data type is being specified as int 16
# therefore the item size is 2 (16/8) bytes currently
print(b.itemsize)

2


In [8]:
# If using default data type float 64 here, then the itemsize is 8 (64/8) bytes
#b = np.array([[3.0, 7.0, 5.0], [6.0, 2.0, 4.0]])
print(b.itemsize)

2


In [9]:
# To get total size, using nbytes
print(b.nbytes)

12


In [10]:
# ACCESSING/CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS, ETC #

a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [11]:
# Get a specific element in the array using [r, c]
print(a[1, 5]) # Forward column 5
print(a[1, -2]) # Backward column -2

13
13


In [12]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [13]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column
print(a[:, 2])

In [ ]:
# Get a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

In [ ]:
# Change one fo the numbers in the array
a[1, 5] = 20
print(a)

In [ ]:
# Change a specific column numbers
a[:, 2] = 7
print(a)

In [ ]:
a[:, 2] = [7, 8]
print(a)

In [14]:
# 3D example
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get a specific element in 3D, for example getting 4
print(b[0, 1, 1])

4


In [19]:
# For example, getting the 1st index row in first array and second array
print(b[:, 1, :])

[[3 4]
 [7 8]]


In [20]:
# Replace the values in the arrays
b[:, 0, :] = [[7, 7], [0, 0]]
print(b)

[[[7 7]
  [3 4]]

 [[0 0]
  [7 8]]]


In [21]:
# INITIALIZING DIFFERENT TYPES OF ARRAYS #

# All 0s matrix
# Give a vector of 5
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [22]:
# Give more complex shape
print(np.zeros((3, 4, 4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [23]:
# All 1s matrix
print(np.ones((3, 3, 3), dtype = 'int32').dtype)

int32


In [24]:
# Any other number. In this case it is 99
print(np.full((3,3), 99))

[[99 99 99]
 [99 99 99]
 [99 99 99]]


In [25]:
# Any other number, full_like method, to change all the numbers
# in arrays to be 4 in this example. It is full_like
print(np.full_like(a, 4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [26]:
# Generate random decimal numbers in array
# 4 is 4 arrays, 2 is 2 row, 2 is 2 columns
print(np.random.rand(4,2,2))
# Hint: A Tuple is a collection of Python objects separated by commas.
# In someways a tuple is similar to a list in terms of indexing, nested objects and
# repetition but a tuple is immutable unlike lists which are mutable.

[[[0.63105594 0.96831711]
  [0.73325368 0.78860214]]

 [[0.12925592 0.26305163]
  [0.90550033 0.92236195]]

 [[0.77193959 0.43926373]
  [0.49113341 0.1573093 ]]

 [[0.42713079 0.01846447]
  [0.89212018 0.35581282]]]


In [27]:
# randomnize a sample data
print(np.random.random_sample(a.shape))

[[0.59645564 0.01978146 0.2322087  0.24337826 0.77453133 0.57875437
  0.29340286]
 [0.1385735  0.83772874 0.05360143 0.76198863 0.57162184 0.15641106
  0.67680672]]


In [28]:
# Random Integer values. For example 5,10 is the range of random integer and
# specify the size of the array as 3 row 3 column
print(np.random.randint(5,10, size = (3, 3)))

[[7 9 9]
 [7 9 9]
 [9 8 8]]


In [29]:
# The identity matrix , square major matrix the mumber you put in
# is the row and column number of the matrix. The number is either 0
# or 1
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [30]:
# To repeat the array a few times
arr = np.array([[7, 8, 9]])
r1 = np.repeat(arr, 5, axis=0)
print(r1)

[[7 8 9]
 [7 8 9]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


In [31]:
# Right way to copy array
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [32]:
# MATHEMATICS #
print(a + 2) # The values in array increases 2

[3 4 5]


In [33]:
a += 2
print(a)

[3 4 5]


In [34]:
print(a - 2) # The values in array decreases 2

[1 2 3]


In [35]:
print(a * 2) # The values in array multiple 2

[ 6  8 10]


In [36]:
print(a / 2) # The values in array divided by 2

[1.5 2.  2.5]


In [37]:
print(a ** 2) # The values in array a to the second power

[ 9 16 25]


In [38]:
print(np.sin(a)) # Take a sin

[ 0.14112001 -0.7568025  -0.95892427]


In [16]:
print(np.cos(a)) # Take a cos

[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
   0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396  0.90744678
   0.13673722]]


In [39]:
# Linear Algebra #

# In linear algebra you need to have the columns of the first matrix
# be equal to the rows of the second one.
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [41]:
# Matrix multiple function
print(np.matmul(a, b))

[[6. 6.]
 [6. 6.]]


In [42]:
# Hint: The indentity mateix has a determinant of one
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [43]:
# STATISTICS #
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats, axis=1))
print(np.max(stats, axis=1))
print(np.sum(stats))

[1 4]
[3 6]
21


In [44]:
# REORGANIZING ARRAYS #
before = np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [45]:
# Using reshape to reshape the row and column of the arrays
after = before.reshape((6, 1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [46]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
# Horizontal stacking vectors, stack to the right
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(np.hstack((h1, h2)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [48]:
# MISCELLANEOUS #

# Load Data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32') # Copy data to whichever format you specify
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [49]:
# Boolean Masking and Advanced Index #

print(filedata > 50)
print(~((filedata > 50) & (filedata < 100))) # file data is not greater than 50 and less than 100
print(filedata[filedata > 50]) # Only print out the filedata that has value greater than 50

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
[196.  75. 766.  75.  55. 999.  78.  76.  88.]


In [50]:
# Index with a list in numPY
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,7]])

[2 3 8]


In [51]:
# If any value in each column is greater than 50
print(np.any(filedata > 50, axis=0))
# If all value in each column is greater than 50
print(np.all(filedata > 50, axis=1))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False]
